#!/usr/bin/env bash
echo off
mkdir project
cd project
mkdir 01-CorrenspondenceIn
mkdir 02-CorrenspondenceOut
mkdir 03-Info
mkdir 04-Calc
mkdir 05-Photos
mkdir 06-Drawings
mkdir 07-Plans
mkdir 08-Templates
mkdir 09-Presentations
mkdir 10-DocumentControl
mkdir 11-Mom
mkdir 12-Notes
mkdir 13-Archive
mkdir 14-TechnicalDocuments
mkdir 15-ReportsAndProgress
mkdir 16-Vendors
mkdir 17-HSE
mkdir 18-Standards
mkdir 19-RulesAndGuides
mkdir 20-MagazinesAndBooks
mkdir 21-ClassComments
mkdir 22-Equipment
mkdir 23-InspectionTracking
mkdir 24-FAT_Reports
mkdir 25-IncomingEquipmentInspections
mkdir 26-ProjectContacts
mkdir 27-Subcontractors
mkdir 28-Budget
